---

- name: get enabled Red Hat products
  redhat.satellite.resource_info:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.organization_name }}"
    resource: "repositories"
  register: redhat_products

- name: set Red Hat products to sync plan
  redhat.satellite.product:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.organization_name }}"
    name: "{{ product }}"
    sync_plan: daily
  loop_control:
    loop_var: product
  with_items:
    - "{{ redhat_products | community.general.json_query('resources[*].product.name') | list | unique }}"
  delegate_to: "{{ delegate_host }}"

