---

# Configures foreman components.
# NOTE: Some foreman components can be mapped to katello components, such as operating systems and hostgroups. These should be run after the configure_katello role is run.
# By default, components with katello component mappings will not run by default. This behavior is controlled by the variable "requires_katello_content".
# There is also an overriding variable called override_run_all that can be used to run all tasks.

- name: configure foreman components that don't require katello content to be present
  block:
    - import_tasks: satellite_settings.yml
      tags: ['configure_satellite_settings']
    - import_tasks: organizations.yml
      tags: ['configure_satellite_organizations']
    - import_tasks: locations.yml
      tags: ['configure_satellite_locations']
    - import_tasks: domains.yml
      tags: ['configure_satellite_domains']
    - import_tasks: subnets.yml
      tags: ['configure_satellite_subnets']
    - import_tasks: compute-resources.yml
      tags: ['configure_satellite_compute_resources']
    - import_tasks: realms.yml
      tags: ['configure_satellite_realms']
  when:
    - not (requires_katello_content) or
      override_run_all

- name: configure foreman components that do require katello content to be present
  block:
    - import_tasks: smart-proxies.yml
      tags: ['configure_satellite_smart_proxies']
    - import_tasks: images.yml
      tags: ['configure_satellite_images']
    - import_tasks: compute-profiles.yml
      tags: ['configure_satellite_compute_profiles']
    - import_tasks: provisioning-templates.yml
      tags: ['configure_satellite_provisioning_templates']
    - import_tasks: partition-tables.yml
      tags: ['configure_satellite_partition_tables']
    - import_tasks: operating-systems.yml
      tags: ['configure_satellite_operating_systems']
    - import_tasks: os-default-templates.yml
      tags: ['configure_satellite_os-default_templates']
    - import_tasks: hostgroups.yml
      tags: ['configure_satellite_hostgroups']
  when:
    - requires_katello_content or
      override_run_all
